version: '3.5'
networks:
  scala-java-demo:
    name: scala-java-demo-net
    driver: bridge

services:
  scala-machine:
    image: hseeberger/scala-sbt:11.0.5_1.3.6_2.12.10
    networks:
      - scala-java-demo
    command: 'sleep 9000'

  java-machine:
    image: adoptopenjdk/openjdk11
    networks:
      - scala-java-demo
    volumes:
      - "../fp-java-demo:/fp-java-demo"
    working_dir: /fp-java-demo
    command: './gradlew clean test'
    # command: 'bash /fp-java-demo/gradlew clean test'


